INSERT INTO PUBLISHER (NAME, EMAIL, PHONE) VALUES ('Macmillan Inc.', 'macmillan@hotmail.com', '555-555-0000')
INSERT INTO PUBLISHER (NAME, EMAIL, PHONE) VALUES ('Simon & Schuster', 'simon.schuster@yahoo.com', '555-555-0001')
INSERT INTO PUBLISHER (NAME, EMAIL, PHONE) VALUES ('J. B. Lippincott & Co.', 'lippincott@bing.com', '555-555-0010')
INSERT INTO PUBLISHER (NAME, EMAIL, PHONE) VALUES ('Charles Scribners Sons', 'charles.scribner@protonmail.com', '555-555-0011')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME) VALUES ('margaret@hotmail.com', 'Individual Author', 'Margaret Mitchell')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME) VALUES ('h.lee@aol.com', 'Individual Author', 'Harper Lee')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME) VALUES ('david@magic.com', 'Individual Author', 'David Copperfield')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME) VALUES ('fsf@aol.com', 'Individual Author', 'F. Scott Fitzgerald')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME) VALUES ('adHoc@gmail.com', 'Ad Hoc Team', 'AH GROUP')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME) VALUES ('adHocTeam@aol.com', 'Ad Hoc Team', 'Ad Hoc Group')
INSERT INTO AUTHORINGENTITY (EMAIL, AUTHORING_ENTITY_TYPE, NAME, HEAD_WRITER, YEAR_FORMED) VALUES ('write_gp@gmail.com', 'Writing Group', 'Cool Writing Group', 'James Stan', 2005)
INSERT INTO BOOK (ISBN, TITLE, YEARPUBLISHED, AUTHORING_ENTITY_EMAIL, PUBLISHER_NAME) VALUES ('978-0-446-36538-3', 'Gone with the Wind', 1936, 'margaret@hotmail.com', 'Macmillan Inc.')
INSERT INTO BOOK (ISBN, TITLE, YEARPUBLISHED, AUTHORING_ENTITY_EMAIL, PUBLISHER_NAME) VALUES ('978-1982112912', 'David Copperfield''s History of Magic', 2021, 'david@magic.com', 'Simon & Schuster')
INSERT INTO BOOK (ISBN, TITLE, YEARPUBLISHED, AUTHORING_ENTITY_EMAIL, PUBLISHER_NAME) VALUES ('978-0446310789', 'To Kill a Mockingbird', 1960, 'h.lee@aol.com', 'J. B. Lippincott & Co.')
INSERT INTO BOOK (ISBN, TITLE, YEARPUBLISHED, AUTHORING_ENTITY_EMAIL, PUBLISHER_NAME) VALUES ('978-0743273565', 'The Great Gatsby', 1925, 'fsf@aol.com', 'Charles Scribners Sons')